"""Global Multi-Continental Music Industry Knowledge Graph Corpus.

Extensively models the global music ecosystem across:
- Europe: Germany, UK, France, Sweden, Netherlands, Italy, Spain
- North America: USA, Canada
- East & South Asia: Japan, South Korea, India
- Latin America & Caribbean: Puerto Rico, Colombia, Brazil, Mexico, Jamaica
- Africa & Oceania: Nigeria, South Africa, Australia

Incorporates parent conglomerates, indie labels, booking agencies, historic recording studios,
mastering suites, super-producers, multi-era artists, cross-border migrations,
and international collaboration bridges.
"""

import logging
from typing import List, Set, Tuple

from agies.graph.extractors.base_extractor import BaseGraphExtractor
from agies.graph.schema import (
    Agency,
    Artist,
    BaseEntity,
    Producer,
    RecordLabel,
    RelationshipEdge,
    RelationshipType,
    Studio,
)

logger = logging.getLogger("agies.graph.corpus")


class GlobalMusicIndustryCorpusExtractor(BaseGraphExtractor):
    """Constructs the comprehensive global multi-continental music industry knowledge graph."""

    def __init__(self):
        super().__init__(name="global_multi_continental_corpus")

    def extract(
        self, query: str = "", limit: int = 2000
    ) -> Tuple[List[BaseEntity], List[RelationshipEdge]]:
        entities: List[BaseEntity] = []
        edges: List[RelationshipEdge] = []
        seen_entities: Set[str] = set()

        def add_ent(e: BaseEntity):
            if e.id not in seen_entities:
                entities.append(e)
                seen_entities.add(e.id)

        # =========================================================================
        # 1. RECORD LABELS & CONGLOMERATES (Across 15+ Nations)
        # =========================================================================
        labels_corpus = [
            # --- GLOBAL PARENT CONGLOMERATES ---
            (
                "lbl_umg_parent",
                "Universal Music Group (UMG)",
                True,
                None,
                ["Parent Conglomerate"],
                "Netherlands / USA",
            ),
            (
                "lbl_sme_parent",
                "Sony Music Entertainment (SME)",
                True,
                None,
                ["Parent Conglomerate"],
                "Japan / USA",
            ),
            (
                "lbl_wmg_parent",
                "Warner Music Group (WMG)",
                True,
                None,
                ["Parent Conglomerate"],
                "USA",
            ),
            (
                "lbl_bmg_parent",
                "BMG Rights Management (Bertelsmann)",
                True,
                None,
                ["Parent Conglomerate"],
                "Germany",
            ),
            ("lbl_beggars", "Beggars Group", False, None, ["Indie Parent Group"], "UK"),
            # --- UNITED STATES ---
            (
                "lbl_interscope",
                "Interscope Geffen A&M",
                True,
                "Universal Music Group (UMG)",
                ["Pop", "Hip-Hop", "Rock"],
                "USA",
            ),
            (
                "lbl_republic",
                "Republic Records",
                True,
                "Universal Music Group (UMG)",
                ["Pop", "R&B", "Hip-Hop"],
                "USA",
            ),
            (
                "lbl_def_jam",
                "Def Jam Recordings",
                True,
                "Universal Music Group (UMG)",
                ["Hip-Hop", "Trap"],
                "USA",
            ),
            (
                "lbl_capitol",
                "Capitol Records",
                True,
                "Universal Music Group (UMG)",
                ["Pop", "Alternative"],
                "USA",
            ),
            (
                "lbl_motown",
                "Motown Records",
                True,
                "Universal Music Group (UMG)",
                ["Soul", "R&B", "Hip-Hop"],
                "USA",
            ),
            (
                "lbl_columbia",
                "Columbia Records",
                True,
                "Sony Music Entertainment (SME)",
                ["Pop", "Rock", "Alternative"],
                "USA",
            ),
            (
                "lbl_rca",
                "RCA Records",
                True,
                "Sony Music Entertainment (SME)",
                ["R&B", "Pop", "Electronic"],
                "USA",
            ),
            (
                "lbl_epic",
                "Epic Records",
                True,
                "Sony Music Entertainment (SME)",
                ["Hip-Hop", "R&B", "Pop"],
                "USA",
            ),
            (
                "lbl_atlantic",
                "Atlantic Records",
                True,
                "Warner Music Group (WMG)",
                ["Hip-Hop", "Pop", "Rock"],
                "USA",
            ),
            (
                "lbl_warner_rec",
                "Warner Records",
                True,
                "Warner Music Group (WMG)",
                ["Pop", "Rock", "Electronic"],
                "USA",
            ),
            (
                "lbl_sub_pop",
                "Sub Pop Records",
                False,
                None,
                ["Grunge", "Indie Rock"],
                "USA",
            ),
            (
                "lbl_stones_throw",
                "Stones Throw Records",
                False,
                None,
                ["Underground Hip-Hop", "Neo-Soul"],
                "USA",
            ),
            (
                "lbl_brainfeeder",
                "Brainfeeder",
                False,
                None,
                ["Experimental", "Jazz Fusion"],
                "USA",
            ),
            (
                "lbl_secretly",
                "Secretly Canadian",
                False,
                None,
                ["Indie Rock", "Folk"],
                "USA",
            ),
            (
                "lbl_ghostly",
                "Ghostly International",
                False,
                None,
                ["Electronic", "Ambient"],
                "USA",
            ),
            ("lbl_mad_decent", "Mad Decent", False, None, ["EDM", "Trap"], "USA"),
            (
                "lbl_rocnation_lbl",
                "Roc Nation Records",
                False,
                "Universal Music Group (UMG)",
                ["Hip-Hop", "R&B"],
                "USA",
            ),
            (
                "lbl_topdawg",
                "Top Dawg Entertainment (TDE)",
                False,
                "Universal Music Group (UMG)",
                ["Hip-Hop", "R&B"],
                "USA",
            ),
            (
                "lbl_pglang",
                "pgLang",
                False,
                None,
                ["Hip-Hop", "Creative Agency"],
                "USA",
            ),
            (
                "lbl_qc",
                "Quality Control Music",
                True,
                "Universal Music Group (UMG)",
                ["Trap", "Hip-Hop"],
                "USA",
            ),
            # --- UNITED KINGDOM ---
            (
                "lbl_island",
                "Island Records",
                True,
                "Universal Music Group (UMG)",
                ["Reggae", "Pop", "Indie"],
                "UK / Jamaica",
            ),
            (
                "lbl_polydor",
                "Polydor Records",
                True,
                "Universal Music Group (UMG)",
                ["Pop", "Electronic"],
                "UK",
            ),
            (
                "lbl_virgin_emi",
                "Virgin EMI Records",
                True,
                "Universal Music Group (UMG)",
                ["Pop", "Urban"],
                "UK",
            ),
            (
                "lbl_parlophone",
                "Parlophone Records",
                True,
                "Warner Music Group (WMG)",
                ["Alternative", "Britpop"],
                "UK",
            ),
            (
                "lbl_4ad",
                "4AD",
                False,
                "Beggars Group",
                ["Dream Pop", "Post-Punk"],
                "UK",
            ),
            (
                "lbl_xl_rec",
                "XL Recordings",
                False,
                "Beggars Group",
                ["Electronic", "Indie Rock"],
                "UK",
            ),
            (
                "lbl_matador",
                "Matador Records",
                False,
                "Beggars Group",
                ["Indie Rock", "Lo-Fi"],
                "UK / USA",
            ),
            (
                "lbl_rough_trade",
                "Rough Trade Records",
                False,
                "Beggars Group",
                ["Post-Punk", "Indie"],
                "UK",
            ),
            (
                "lbl_warp",
                "Warp Records",
                False,
                None,
                ["Electronic", "IDM", "Experimental"],
                "UK",
            ),
            (
                "lbl_ninja_tune",
                "Ninja Tune",
                False,
                None,
                ["Electronic", "Trip-Hop"],
                "UK",
            ),
            (
                "lbl_domino",
                "Domino Recording Company",
                False,
                None,
                ["Indie Rock", "Folktronica"],
                "UK",
            ),
            # --- GERMANY ---
            (
                "lbl_dg",
                "Deutsche Grammophon",
                True,
                "Universal Music Group (UMG)",
                ["Classical", "Post-Classical"],
                "Germany",
            ),
            (
                "lbl_kompakt",
                "Kompakt Records",
                False,
                None,
                ["Techno", "Minimal", "Ambient"],
                "Germany",
            ),
            (
                "lbl_ostgut",
                "Ostgut Ton",
                False,
                None,
                ["Berghain Techno", "Industrial"],
                "Germany",
            ),
            (
                "lbl_innervisions",
                "Innervisions",
                False,
                None,
                ["Deep House", "Melodic Techno"],
                "Germany",
            ),
            (
                "lbl_tresor",
                "Tresor Records",
                False,
                None,
                ["Detroit-Berlin Techno"],
                "Germany",
            ),
            (
                "lbl_boysnoize",
                "Boysnoize Records",
                False,
                None,
                ["Electro", "Industrial"],
                "Germany",
            ),
            (
                "lbl_erasedtapes",
                "Erased Tapes",
                False,
                None,
                ["Post-Classical", "Ambient"],
                "Germany / UK",
            ),
            # --- NETHERLANDS ---
            (
                "lbl_spinnin",
                "Spinnin' Records",
                True,
                "Warner Music Group (WMG)",
                ["EDM", "House", "Dance"],
                "Netherlands",
            ),
            (
                "lbl_armada",
                "Armada Music",
                False,
                None,
                ["Trance", "Progressive", "EDM"],
                "Netherlands",
            ),
            # --- FRANCE ---
            (
                "lbl_edbanger",
                "Ed Banger Records",
                False,
                None,
                ["French Touch", "Electro House"],
                "France",
            ),
            (
                "lbl_because",
                "Because Music",
                False,
                None,
                ["French Pop", "Electronic"],
                "France",
            ),
            (
                "lbl_kitsune",
                "Kitsuné Musique",
                False,
                None,
                ["Indie Dance", "Nu-Disco"],
                "France",
            ),
            # --- SWEDEN & NORDICS ---
            (
                "lbl_mxm_prod",
                "MXM Music Productions",
                False,
                None,
                ["Global Pop", "Dance-Pop"],
                "Sweden",
            ),
            (
                "lbl_ten_music",
                "TEN Music Group",
                False,
                None,
                ["Pop", "Electronic"],
                "Sweden",
            ),
            (
                "lbl_stockholm_rec",
                "Stockholm Records",
                True,
                "Universal Music Group (UMG)",
                ["Pop", "Eurodance"],
                "Sweden",
            ),
            (
                "lbl_smekkleysa",
                "Bad Taste Records (Smekkleysa)",
                False,
                None,
                ["Art Rock", "Avant-Garde"],
                "Iceland",
            ),
            # --- JAPAN ---
            (
                "lbl_avex",
                "Avex Group",
                True,
                None,
                ["J-Pop", "Anime", "Dance"],
                "Japan",
            ),
            (
                "lbl_sony_japan",
                "Sony Music Entertainment Japan (SMEJ)",
                True,
                "Sony Music Entertainment (SME)",
                ["J-Pop", "Anisong"],
                "Japan",
            ),
            (
                "lbl_victor_jp",
                "Victor Entertainment",
                False,
                None,
                ["City Pop", "Rock"],
                "Japan",
            ),
            (
                "lbl_king_rec",
                "King Records",
                False,
                None,
                ["Anisong", "Soundtracks"],
                "Japan",
            ),
            # --- SOUTH KOREA ---
            (
                "lbl_hybe_corp",
                "HYBE Labels (Big Hit / ADOR / Pledis)",
                False,
                None,
                ["K-Pop", "Dance-Pop"],
                "South Korea",
            ),
            (
                "lbl_sm_ent",
                "SM Entertainment",
                False,
                None,
                ["K-Pop", "SMP", "R&B"],
                "South Korea",
            ),
            (
                "lbl_yg_ent",
                "YG Entertainment",
                False,
                None,
                ["K-Pop", "Hip-Hop"],
                "South Korea",
            ),
            (
                "lbl_jyp_ent",
                "JYP Entertainment",
                False,
                None,
                ["K-Pop", "Dance-Pop"],
                "South Korea",
            ),
            # --- INDIA ---
            (
                "lbl_tseries",
                "T-Series",
                True,
                None,
                ["Bollywood", "Pop", "Soundtracks"],
                "India",
            ),
            (
                "lbl_yrf_music",
                "YRF Music (Yash Raj Films)",
                True,
                None,
                ["Cinematic", "Bollywood"],
                "India",
            ),
            (
                "lbl_gully_gang",
                "Gully Gang Records",
                False,
                None,
                ["Desi Hip-Hop", "Street Rap"],
                "India",
            ),
            # --- JAMAICA & CARIBBEAN ---
            (
                "lbl_tuffgong_lbl",
                "Tuff Gong Records",
                False,
                None,
                ["Reggae", "Roots", "Dub"],
                "Jamaica",
            ),
            (
                "lbl_studio_one",
                "Studio One",
                False,
                None,
                ["Ska", "Rocksteady"],
                "Jamaica",
            ),
            (
                "lbl_vp_rec",
                "VP Records",
                False,
                None,
                ["Dancehall", "Reggae"],
                "Jamaica / USA",
            ),
            (
                "lbl_trojan",
                "Trojan Records",
                False,
                "BMG Rights Management (Bertelsmann)",
                ["Reggae", "Dub"],
                "Jamaica / UK",
            ),
            # --- NIGERIA & SOUTH AFRICA ---
            (
                "lbl_mavin",
                "Mavin Records",
                False,
                "Universal Music Group (UMG)",
                ["Afrobeats", "Afropop"],
                "Nigeria",
            ),
            (
                "lbl_starboy",
                "Starboy Entertainment",
                False,
                "Sony Music Entertainment (SME)",
                ["Afrobeats"],
                "Nigeria",
            ),
            (
                "lbl_spaceship",
                "Spaceship Records",
                False,
                "Atlantic Records",
                ["Afro-Fusion"],
                "Nigeria",
            ),
            (
                "lbl_ybnl",
                "YBNL Nation",
                False,
                "Empire Distribution",
                ["Afrobeats", "Street"],
                "Nigeria",
            ),
            (
                "lbl_soulistic",
                "Soulistic Music",
                False,
                None,
                ["Afro-House", "Deep House"],
                "South Africa",
            ),
            ("lbl_pianohub", "Piano Hub", False, None, ["Amapiano"], "South Africa"),
            # --- BRAZIL, COLOMBIA, PUERTO RICO & MEXICO ---
            (
                "lbl_somlivre",
                "Som Livre",
                True,
                "Sony Music Entertainment (SME)",
                ["Bossa Nova", "Sertanejo", "MPB"],
                "Brazil",
            ),
            (
                "lbl_kondzilla",
                "KondZilla Records",
                False,
                None,
                ["Baile Funk", "Funk Mandelão"],
                "Brazil",
            ),
            (
                "lbl_rimas",
                "Rimas Entertainment",
                False,
                None,
                ["Reggaeton", "Latin Trap"],
                "Puerto Rico",
            ),
            (
                "lbl_hearthismusic",
                "Hear This Music",
                False,
                None,
                ["Latin Trap", "Urban"],
                "Puerto Rico",
            ),
            (
                "lbl_richmusic",
                "Rich Music",
                False,
                None,
                ["Reggaeton", "Latin Pop"],
                "Colombia / USA",
            ),
            # --- AUSTRALIA ---
            (
                "lbl_futureclassic",
                "Future Classic",
                False,
                None,
                ["Electronic", "Indie Dance"],
                "Australia",
            ),
            (
                "lbl_modular",
                "Modular Recordings",
                True,
                "Universal Music Group (UMG)",
                ["Indie Dance", "Psychedelic"],
                "Australia",
            ),
            # --- CANADA ---
            (
                "lbl_ovo",
                "OVO Sound",
                False,
                "Warner Music Group (WMG)",
                ["Hip-Hop", "R&B", "Toronto Sound"],
                "Canada",
            ),
            (
                "lbl_xo",
                "XO Records",
                False,
                "Universal Music Group (UMG)",
                ["R&B", "Synthwave"],
                "Canada",
            ),
            (
                "lbl_monstercat",
                "Monstercat",
                False,
                None,
                ["Electronic", "Bass Music"],
                "Canada",
            ),
            (
                "lbl_arts_crafts",
                "Arts & Crafts",
                False,
                None,
                ["Indie Rock", "Post-Rock"],
                "Canada",
            ),
        ]

        for lid, name, is_major, parent, genres, country in labels_corpus:
            lbl = RecordLabel(
                id=lid,
                name=name,
                is_major=is_major,
                parent_company=parent,
                genres=genres,
                country=country,
                attributes={
                    "market_tier": "Major Conglomerate" if is_major else "Independent"
                },
            )
            add_ent(lbl)
            if parent:
                parent_id = (
                    "lbl_umg_parent"
                    if "Universal" in parent
                    else (
                        "lbl_sme_parent"
                        if "Sony" in parent
                        else (
                            "lbl_wmg_parent"
                            if "Warner" in parent
                            else (
                                "lbl_bmg_parent"
                                if "BMG" in parent or "Bertelsmann" in parent
                                else (
                                    "lbl_beggars"
                                    if "Beggars" in parent
                                    else (
                                        "lbl_atlantic"
                                        if "Atlantic" in parent
                                        else "lbl_umg_parent"
                                    )
                                )
                            )
                        )
                    )
                )
                edges.append(
                    RelationshipEdge(
                        source_id=parent_id,
                        target_id=lid,
                        rel_type=RelationshipType.PARENT_COMPANY_OF,
                        weight=1.0,
                    )
                )

        # =========================================================================
        # 2. GLOBAL TALENT & MANAGEMENT AGENCIES
        # =========================================================================
        agencies_corpus = [
            ("ag_wme", "WME (William Morris Endeavor)", "Booking", "USA / Global"),
            ("ag_caa", "CAA (Creative Artists Agency)", "Booking", "USA / Global"),
            ("ag_uta", "UTA (United Talent Agency)", "Booking", "USA / Global"),
            ("ag_wasserman", "Wasserman Music", "Booking", "UK / USA"),
            ("ag_rocnation", "Roc Nation Management", "Management", "USA / Global"),
            ("ag_redlight", "Red Light Management", "Management", "USA"),
            ("ag_fullstop", "Full Stop Management", "Management", "USA"),
            (
                "ag_sbprojects",
                "SB Projects (HYBE America)",
                "Management",
                "USA / South Korea",
            ),
            ("ag_qprime", "Q Prime Management", "Management", "USA / UK"),
            ("ag_threesixzero", "Three Six Zero", "Management", "UK / USA"),
            ("ag_primary", "Primary Talent International", "Booking", "UK / Europe"),
            (
                "ag_kakaom",
                "Kakao Entertainment Management",
                "Management",
                "South Korea",
            ),
            ("ag_tm_talent", "TM Talent Management India", "Management", "India"),
        ]

        for aid, name, atype, reg in agencies_corpus:
            ag = Agency(
                id=aid,
                name=name,
                agency_type=atype,
                country=reg,
                attributes={"region": reg},
            )
            add_ent(ag)

        # =========================================================================
        # 3. WORLD-CLASS RECORDING & MASTERING STUDIOS
        # =========================================================================
        studios_corpus = [
            # United Kingdom
            ("std_abbey", "Abbey Road Studios", "London", "UK", "Legendary / Tier A+"),
            (
                "std_air",
                "AIR Studios (Lyndhurst Hall)",
                "London",
                "UK",
                "Orchestral / Tier A+",
            ),
            (
                "std_metropolis",
                "Metropolis Studios",
                "London",
                "UK",
                "Mastering / Tier A",
            ),
            ("std_rak", "RAK Studios", "London", "UK", "Boutique / Tier A"),
            # Germany
            (
                "std_hansa",
                "Hansa Studios (Hansa Tonstudio)",
                "Berlin",
                "Germany",
                "Historic / Berlin Sound / Tier A+",
            ),
            (
                "std_funkhaus",
                "Funkhaus Berlin (Saal 1)",
                "Berlin",
                "Germany",
                "World's Largest Acoustic Complex / Tier A+",
            ),
            (
                "std_klingklang",
                "Kling Klang Studio",
                "Düsseldorf",
                "Germany",
                "Birthplace of Electronic Music / Historic",
            ),
            (
                "std_teldex",
                "Teldex Studio Berlin",
                "Berlin",
                "Germany",
                "Acoustic & Classical / Tier A+",
            ),
            (
                "std_emilberliner",
                "Emil Berliner Studios",
                "Berlin",
                "Germany",
                "Pure Analog Mastering / Tier A",
            ),
            # United States
            (
                "std_electric",
                "Electric Lady Studios",
                "New York",
                "USA",
                "Legendary / Tier A+",
            ),
            (
                "std_sunset",
                "Sunset Sound Recorders",
                "Los Angeles",
                "USA",
                "Historic / Tier A",
            ),
            (
                "std_conway",
                "Conway Recording Studios",
                "Los Angeles",
                "USA",
                "Elite / Tier A",
            ),
            (
                "std_capitol",
                "Capitol Studios",
                "Los Angeles",
                "USA",
                "Historic / Tier A",
            ),
            (
                "std_oceanway",
                "Ocean Way Recording",
                "Nashville",
                "USA",
                "Acoustic / Tier A",
            ),
            (
                "std_blackbird",
                "Blackbird Studio",
                "Nashville",
                "USA",
                "Gear Paradise / Tier A+",
            ),
            (
                "std_criteria",
                "Criteria Recording Studios (Hit Factory)",
                "Miami",
                "USA",
                "R&B / Hip-Hop / Tier A",
            ),
            (
                "std_soundcity",
                "Sound City Studios",
                "Los Angeles",
                "USA",
                "Analog Rock / Tier A",
            ),
            # France
            (
                "std_motorbass",
                "Motorbass Studio",
                "Paris",
                "France",
                "French Touch / Vintage Analog / Tier A",
            ),
            (
                "std_grandearmee",
                "Studio Grande Armée",
                "Paris",
                "France",
                "Historic French / Tier A",
            ),
            # Sweden & Iceland
            (
                "std_maratone",
                "Cheiron & Maratone Studios",
                "Stockholm",
                "Sweden",
                "Global Pop Hit Factory / Tier A+",
            ),
            (
                "std_greenhouse",
                "Greenhouse Studios",
                "Reykjavik",
                "Iceland",
                "Atmospheric & Cinematic / Tier A",
            ),
            # Netherlands
            (
                "std_wisseloord",
                "Wisseloord Studios",
                "Hilversum",
                "Netherlands",
                "Historic European / Tier A+",
            ),
            # Japan
            (
                "std_sonytokyo",
                "Sony Music Studios Tokyo",
                "Tokyo",
                "Japan",
                "Precision Acoustic / Tier A+",
            ),
            (
                "std_ghibli",
                "Studio Ghibli Scoring Stage",
                "Tokyo",
                "Japan",
                "Cinematic Orchestral / Historic",
            ),
            # South Korea
            (
                "std_hybe_std",
                "HYBE Creative Studios",
                "Seoul",
                "South Korea",
                "High-Tech K-Pop / Tier A+",
            ),
            # India
            (
                "std_panchathan",
                "Panchathan Record Inn (AM Studios)",
                "Chennai",
                "India",
                "Cinematic Fusion / Tier A+",
            ),
            (
                "std_yashraj",
                "YRF Studios",
                "Mumbai",
                "India",
                "Bollywood Scoring / Tier A",
            ),
            # Jamaica
            (
                "std_tuffgong",
                "Tuff Gong Studio",
                "Kingston",
                "Jamaica",
                "Reggae & Roots / Historic / Tier A",
            ),
            (
                "std_blackark",
                "The Black Ark (Lee Perry)",
                "Kingston",
                "Jamaica",
                "Dub Origin / Historic",
            ),
            # Nigeria & South Africa
            (
                "std_mavin_std",
                "Mavin Creative Studios",
                "Lagos",
                "Nigeria",
                "Afrobeats HQ / Tier A",
            ),
            (
                "std_soulistic_std",
                "Soulistic Sound Lab",
                "Johannesburg",
                "South Africa",
                "Afro-House / Tier A",
            ),
            # Brazil & Colombia
            (
                "std_nasnuvens",
                "Nas Nuvens Studio",
                "Rio de Janeiro",
                "Brazil",
                "Historic Brazilian / Tier A",
            ),
            (
                "std_elalto",
                "El Alto Studio",
                "Medellín",
                "Colombia",
                "Reggaeton HQ / Tier A",
            ),
            # Canada & Australia
            (
                "std_metalworks",
                "Metalworks Studios",
                "Toronto",
                "Canada",
                "Toronto Sound / Tier A",
            ),
            (
                "std_studios301",
                "Studios 301",
                "Sydney",
                "Australia",
                "Southern Hemisphere Bench / Tier A+",
            ),
        ]

        for sid, name, city, country, tier in studios_corpus:
            st = Studio(
                id=sid, name=name, city=city, country=country, equipment_tier=tier
            )
            add_ent(st)

        # =========================================================================
        # 4. SUPER-PRODUCERS & SONIC ARCHITECTS
        # =========================================================================
        producers_corpus = [
            # Sweden (Global Hitmakers)
            (
                "prd_max",
                "Max Martin",
                "Global Pop Hit Architect",
                ["Pop", "Dance", "Synthpop"],
                "Sweden",
            ),
            (
                "prd_shellback",
                "Shellback (Johan Schuster)",
                "Pop & Rock Hit Producer",
                ["Pop", "Rock"],
                "Sweden",
            ),
            (
                "prd_goransson",
                "Ludwig Göransson",
                "Film Score & Hip-Hop Architect",
                ["Cinematic", "Hip-Hop"],
                "Sweden",
            ),
            (
                "prd_bloodshy",
                "Bloodshy & Avant",
                "Electropop Pioneers",
                ["Pop", "Electro"],
                "Sweden",
            ),
            # United States
            (
                "prd_jack",
                "Jack Antonoff",
                "Indie Pop / Folk Architect",
                ["Indie Pop", "Alternative", "Folk"],
                "USA",
            ),
            (
                "prd_rick",
                "Rick Rubin",
                "Sonic Architect & Exec Producer",
                ["Rock", "Hip-Hop", "Metal"],
                "USA",
            ),
            (
                "prd_metro",
                "Metro Boomin",
                "Trap & Hip-Hop Exec Producer",
                ["Hip-Hop", "Trap"],
                "USA",
            ),
            (
                "prd_finneas",
                "Finneas O'Connell",
                "Pop Producer & Songwriter",
                ["Pop", "Minimalist"],
                "USA",
            ),
            (
                "prd_drdre",
                "Dr. Dre",
                "West Coast Hip-Hop Pioneer",
                ["Hip-Hop", "G-Funk"],
                "USA",
            ),
            (
                "prd_pharrell",
                "Pharrell Williams (The Neptunes)",
                "Hitmaker & Sonic Pioneer",
                ["Hip-Hop", "Funk", "Pop"],
                "USA",
            ),
            (
                "prd_timbaland",
                "Timbaland",
                "R&B & Pop Innovator",
                ["R&B", "Hip-Hop", "Pop"],
                "USA",
            ),
            (
                "prd_mikedean",
                "Mike Dean",
                "Synth Maestro & Audio Engineer",
                ["Hip-Hop", "Synth", "Psychedelic"],
                "USA",
            ),
            (
                "prd_greg",
                "Greg Kurstin",
                "Multi-Instrumentalist Producer",
                ["Pop", "Indie Rock"],
                "USA",
            ),
            (
                "prd_butch",
                "Butch Vig",
                "Grunge & Rock Producer",
                ["Grunge", "Rock"],
                "USA",
            ),
            (
                "prd_skrillex",
                "Skrillex (Sonny Moore)",
                "Bass & Electronic Pop Innovator",
                ["Dubstep", "EDM", "Pop"],
                "USA",
            ),
            # Germany
            (
                "prd_zimmer",
                "Hans Zimmer",
                "World #1 Cinematic Film Composer",
                ["Cinematic", "Orchestral"],
                "Germany",
            ),
            (
                "prd_giorgio",
                "Giorgio Moroder",
                "Father of Euro Disco & Synth",
                ["Disco", "Synthwave"],
                "Germany / Italy",
            ),
            (
                "prd_connyplank",
                "Conny Plank",
                "Krautrock & Electronic Pioneer",
                ["Krautrock", "Electronic"],
                "Germany",
            ),
            (
                "prd_nilsfrahm",
                "Nils Frahm",
                "Modern Classical & Acoustic Innovator",
                ["Neo-Classical", "Ambient"],
                "Germany",
            ),
            (
                "prd_paulvandyk",
                "Paul van Dyk",
                "Trance & Electronic Pioneer",
                ["Trance", "Electronic"],
                "Germany",
            ),
            (
                "prd_boysnoize",
                "Boys Noize (Alex Ridha)",
                "Industrial & Electronic Producer",
                ["Electro", "Industrial"],
                "Germany",
            ),
            (
                "prd_stephanbodzin",
                "Stephan Bodzin",
                "Melodic Techno Synthesist",
                ["Melodic Techno", "Synth"],
                "Germany",
            ),
            # United Kingdom
            (
                "prd_brian",
                "Brian Eno",
                "Ambient & Avant-Garde Pioneer",
                ["Ambient", "Electronic", "Art Rock"],
                "UK",
            ),
            (
                "prd_nigel",
                "Nigel Godrich",
                "Sonic Experimentalist",
                ["Art Rock", "Alternative"],
                "UK",
            ),
            (
                "prd_georgemartin",
                "George Martin",
                "Beatles Producer / 5th Beatle",
                ["Classic Rock", "Orchestral"],
                "UK",
            ),
            # France
            (
                "prd_daft_thomas",
                "Thomas Bangalter (Daft Punk)",
                "French Touch & Electro Pioneer",
                ["French Touch", "House"],
                "France",
            ),
            (
                "prd_pedrowinter",
                "Pedro Winter (Busy P)",
                "Electro House Architect",
                ["Electro House", "Indie Dance"],
                "France",
            ),
            # Netherlands
            (
                "prd_tiesto_prd",
                "Tiësto",
                "Dutch Electronic Dance Master",
                ["Trance", "EDM", "House"],
                "Netherlands",
            ),
            # Japan
            (
                "prd_sakamoto_prd",
                "Ryuichi Sakamoto",
                "Electronic & Cinematic Master",
                ["Ambient", "Electronic", "Classical"],
                "Japan",
            ),
            (
                "prd_hisaishi_prd",
                "Joe Hisaishi",
                "Studio Ghibli Orchestral Composer",
                ["Orchestral", "Cinematic"],
                "Japan",
            ),
            (
                "prd_nujabes_prd",
                "Nujabes (Jun Seba)",
                "Lo-Fi Hip-Hop Founding Father",
                ["Lo-Fi", "Jazz Rap"],
                "Japan",
            ),
            # South Korea
            (
                "prd_hitman",
                "Bang Si-hyuk (Hitman Bang)",
                "K-Pop Executive Architect",
                ["K-Pop", "Hip-Hop"],
                "South Korea",
            ),
            (
                "prd_teddypark",
                "Teddy Park",
                "K-Pop & Hip-Hop Hitmaker",
                ["K-Pop", "EDM"],
                "South Korea",
            ),
            (
                "prd_pdogg",
                "Pdogg",
                "BTS Chief Music Producer",
                ["Hip-Hop", "Pop"],
                "South Korea",
            ),
            # India
            (
                "prd_arrahman",
                "A.R. Rahman",
                "Mozart of Madras / Global Fusion Maestro",
                ["Cinematic", "World", "Classical"],
                "India",
            ),
            # Jamaica
            (
                "prd_kingtubby",
                "King Tubby",
                "Father of Dub & Remix Culture",
                ["Dub", "Reggae"],
                "Jamaica",
            ),
            (
                "prd_leeperry",
                "Lee 'Scratch' Perry",
                "Dub & Roots Visionary",
                ["Dub", "Reggae"],
                "Jamaica",
            ),
            # Nigeria & South Africa
            (
                "prd_donjazzy",
                "Don Jazzy",
                "Afrobeats Executive Producer",
                ["Afrobeats", "Afropop"],
                "Nigeria",
            ),
            (
                "prd_sarz",
                "Sarz",
                "Afro-Fusion & Beat Innovator",
                ["Afro-Fusion", "Afropop"],
                "Nigeria",
            ),
            (
                "prd_blackcoffee_prd",
                "Black Coffee",
                "Afro-House World Pioneer",
                ["Afro-House", "Deep House"],
                "South Africa",
            ),
            # Latin America
            (
                "prd_tainy",
                "Tainy (Marco Masís)",
                "Reggaeton & Latin Trap Architect",
                ["Reggaeton", "Latin Trap"],
                "Puerto Rico",
            ),
            (
                "prd_ovydrums",
                "Ovy On The Drums",
                "Latin Urban & Pop Hitmaker",
                ["Reggaeton", "Pop"],
                "Colombia",
            ),
            # Canada & Australia
            (
                "prd_40",
                "Noah '40' Shebib",
                "Toronto Sound Architect",
                ["Hip-Hop", "R&B"],
                "Canada",
            ),
            (
                "prd_kaytranada_prd",
                "KAYTRANADA",
                "Afro-House & Neo-Soul Producer",
                ["Neo-Soul", "House"],
                "Canada",
            ),
            (
                "prd_kevinparker",
                "Kevin Parker (Tame Impala)",
                "Psychedelic & Synth Architect",
                ["Psychedelic", "Synthpop"],
                "Australia",
            ),
        ]

        for pid, name, role, pgenres, pcountry in producers_corpus:
            p = Producer(id=pid, name=name, role=role, genres=pgenres, country=pcountry)
            add_ent(p)

        # =========================================================================
        # 5. GLOBAL ARTISTS CORPUS (Comprehensive Multi-Continental Roster)
        # =========================================================================
        artists_corpus = [
            # === UNITED STATES ===
            (
                "art_taylor",
                "Taylor Swift",
                "Person",
                ["Pop", "Country", "Indie Folk"],
                2004,
                "USA",
                "lbl_republic",
                "ag_wme",
                "prd_jack",
                "std_electric",
            ),
            (
                "art_billie",
                "Billie Eilish",
                "Person",
                ["Pop", "Alternative"],
                2015,
                "USA",
                "lbl_interscope",
                "ag_wme",
                "prd_finneas",
                "std_sunset",
            ),
            (
                "art_kendrick",
                "Kendrick Lamar",
                "Person",
                ["Hip-Hop", "Jazz Rap"],
                2004,
                "USA",
                "lbl_pglang",
                "ag_wme",
                "prd_rick",
                "std_conway",
            ),
            (
                "art_kanye",
                "Ye (Kanye West)",
                "Person",
                ["Hip-Hop", "Art Pop"],
                2000,
                "USA",
                "lbl_def_jam",
                "ag_rocnation",
                "prd_mikedean",
                "std_electric",
            ),
            (
                "art_eminem",
                "Eminem",
                "Person",
                ["Hip-Hop", "Hardcore Rap"],
                1996,
                "USA",
                "lbl_interscope",
                "ag_wme",
                "prd_drdre",
                "std_conway",
            ),
            (
                "art_travisscott",
                "Travis Scott",
                "Person",
                ["Trap", "Psychedelic Rap"],
                2012,
                "USA",
                "lbl_epic",
                "ag_caa",
                "prd_mikedean",
                "std_conway",
            ),
            (
                "art_future",
                "Future",
                "Person",
                ["Hip-Hop", "Trap"],
                2010,
                "USA",
                "lbl_epic",
                "ag_uta",
                "prd_metro",
                "std_conway",
            ),
            (
                "art_21savage",
                "21 Savage",
                "Person",
                ["Hip-Hop", "Trap"],
                2014,
                "USA",
                "lbl_epic",
                "ag_uta",
                "prd_metro",
                "std_conway",
            ),
            (
                "art_beyonce",
                "Beyoncé",
                "Person",
                ["R&B", "Pop", "House"],
                1997,
                "USA",
                "lbl_columbia",
                "ag_rocnation",
                "prd_pharrell",
                "std_conway",
            ),
            (
                "art_sza",
                "SZA",
                "Person",
                ["Neo-Soul", "R&B"],
                2012,
                "USA",
                "lbl_topdawg",
                "ag_wme",
                None,
                "std_conway",
            ),
            (
                "art_nirvana",
                "Nirvana",
                "Group",
                ["Grunge", "Alternative Rock"],
                1987,
                "USA",
                "lbl_sub_pop",
                "ag_qprime",
                "prd_butch",
                "std_soundcity",
            ),
            (
                "art_foo",
                "Foo Fighters",
                "Group",
                ["Post-Grunge", "Hard Rock"],
                1994,
                "USA",
                "lbl_rca",
                "ag_qprime",
                "prd_butch",
                "std_soundcity",
            ),
            (
                "art_redhot",
                "Red Hot Chili Peppers",
                "Group",
                ["Funk Rock", "Alternative"],
                1983,
                "USA",
                "lbl_warner_rec",
                "ag_qprime",
                "prd_rick",
                "std_oceanway",
            ),
            (
                "art_phoebe",
                "Phoebe Bridgers",
                "Person",
                ["Indie Rock", "Folk"],
                2014,
                "USA",
                "lbl_secretly",
                "ag_redlight",
                "prd_jack",
                "std_electric",
            ),
            (
                "art_clairo",
                "Clairo",
                "Person",
                ["Bedroom Pop", "Indie Pop"],
                2017,
                "USA",
                "lbl_republic",
                "ag_wme",
                "prd_jack",
                "std_electric",
            ),
            (
                "art_skrillex_art",
                "Skrillex",
                "Person",
                ["Dubstep", "EDM", "Pop"],
                2008,
                "USA",
                "lbl_atlantic",
                "ag_wasserman",
                "prd_skrillex",
                "std_sunset",
            ),
            (
                "art_flyinglotus",
                "Flying Lotus",
                "Person",
                ["Experimental Hip-Hop", "Jazz Fusion"],
                2005,
                "USA",
                "lbl_warp",
                "ag_wme",
                None,
                "std_electric",
            ),
            # === UNITED KINGDOM ===
            (
                "art_beatles",
                "The Beatles",
                "Group",
                ["Classic Rock", "Psychedelic Pop"],
                1960,
                "UK",
                "lbl_parlophone",
                None,
                "prd_georgemartin",
                "std_abbey",
            ),
            (
                "art_queen",
                "Queen",
                "Group",
                ["Glam Rock", "Arena Rock"],
                1970,
                "UK",
                "lbl_virgin_emi",
                "ag_caa",
                None,
                "std_abbey",
            ),
            (
                "art_radiohead",
                "Radiohead",
                "Group",
                ["Art Rock", "Alternative Rock", "Electronic"],
                1985,
                "UK",
                "lbl_xl_rec",
                "ag_wme",
                "prd_nigel",
                "std_abbey",
            ),
            (
                "art_adele",
                "Adele",
                "Person",
                ["Pop", "Soul"],
                2006,
                "UK",
                "lbl_columbia",
                "ag_wme",
                "prd_greg",
                "std_air",
            ),
            (
                "art_dua",
                "Dua Lipa",
                "Person",
                ["Pop", "Disco"],
                2015,
                "UK",
                "lbl_warner_rec",
                "ag_caa",
                "prd_max",
                "std_rak",
            ),
            (
                "art_harry",
                "Harry Styles",
                "Person",
                ["Pop", "Soft Rock"],
                2010,
                "UK",
                "lbl_columbia",
                "ag_caa",
                "prd_jack",
                "std_sunset",
            ),
            (
                "art_arctic",
                "Arctic Monkeys",
                "Group",
                ["Indie Rock", "Garage Rock"],
                2002,
                "UK",
                "lbl_domino",
                "ag_wme",
                None,
                "std_abbey",
            ),
            (
                "art_aphex",
                "Aphex Twin",
                "Person",
                ["Electronic", "IDM", "Ambient"],
                1985,
                "UK",
                "lbl_warp",
                "ag_primary",
                "prd_brian",
                "std_metropolis",
            ),
            (
                "art_fourtet",
                "Four Tet",
                "Person",
                ["Electronic", "Folktronica"],
                1997,
                "UK",
                "lbl_ninja_tune",
                "ag_primary",
                "prd_brian",
                "std_abbey",
            ),
            (
                "art_bicep",
                "BICEP",
                "Group",
                ["Electronic", "Breakbeat"],
                2009,
                "UK",
                "lbl_ninja_tune",
                "ag_primary",
                None,
                "std_rak",
            ),
            (
                "art_bonobo",
                "Bonobo",
                "Person",
                ["Electronic", "Downtempo"],
                1999,
                "UK",
                "lbl_ninja_tune",
                "ag_redlight",
                None,
                "std_abbey",
            ),
            (
                "art_calvin",
                "Calvin Harris",
                "Person",
                ["EDM", "Dance-Pop"],
                2006,
                "UK",
                "lbl_columbia",
                "ag_threesixzero",
                None,
                "std_metropolis",
            ),
            (
                "art_davidbowie",
                "David Bowie",
                "Person",
                ["Art Rock", "Glam Rock", "Berlin Era"],
                1962,
                "UK",
                "lbl_parlophone",
                "ag_wme",
                "prd_brian",
                "std_hansa",
            ),
            (
                "art_depechemode",
                "Depeche Mode",
                "Group",
                ["Synthpop", "Industrial Rock"],
                1980,
                "UK",
                "lbl_columbia",
                "ag_wme",
                "prd_brian",
                "std_hansa",
            ),
            (
                "art_massiveattack",
                "Massive Attack",
                "Group",
                ["Trip-Hop", "Dub", "Electronica"],
                1988,
                "UK",
                "lbl_virgin_emi",
                "ag_primary",
                None,
                "std_abbey",
            ),
            # === GERMANY ===
            (
                "art_kraftwerk",
                "Kraftwerk",
                "Group",
                ["Electronic", "Synthpop", "Krautrock"],
                1970,
                "Germany",
                "lbl_parlophone",
                "ag_primary",
                "prd_connyplank",
                "std_klingklang",
            ),
            (
                "art_rammstein",
                "Rammstein",
                "Group",
                ["Neue Deutsche Härte", "Industrial Metal"],
                1994,
                "Germany",
                "lbl_polydor",
                "ag_qprime",
                None,
                "std_teldex",
            ),
            (
                "art_scorpions",
                "Scorpions",
                "Group",
                ["Hard Rock", "Heavy Metal"],
                1965,
                "Germany",
                "lbl_bmg_parent",
                "ag_qprime",
                None,
                "std_soundcity",
            ),
            (
                "art_nilsfrahm_art",
                "Nils Frahm",
                "Person",
                ["Neo-Classical", "Ambient", "Minimalism"],
                2005,
                "Germany",
                "lbl_erasedtapes",
                "ag_primary",
                "prd_nilsfrahm",
                "std_funkhaus",
            ),
            (
                "art_modeselektor",
                "Modeselektor / Moderat",
                "Group",
                ["IDM", "Electronic", "Techno"],
                2002,
                "Germany",
                "lbl_ninja_tune",
                "ag_primary",
                None,
                "std_funkhaus",
            ),
            (
                "art_paulvandyk_art",
                "Paul van Dyk",
                "Person",
                ["Trance", "Electronic"],
                1991,
                "Germany",
                "lbl_spinnin",
                "ag_wasserman",
                "prd_paulvandyk",
                "std_hansa",
            ),
            (
                "art_borisbrejcha",
                "Boris Brejcha",
                "Person",
                ["High-Tech Minimal", "Techno"],
                2006,
                "Germany",
                "lbl_spinnin",
                "ag_wasserman",
                None,
                "std_hansa",
            ),
            (
                "art_robinschulz",
                "Robin Schulz",
                "Person",
                ["Deep House", "Dance-Pop"],
                2013,
                "Germany",
                "lbl_warner_rec",
                "ag_caa",
                None,
                "std_hansa",
            ),
            (
                "art_stephanbodzin_art",
                "Stephan Bodzin",
                "Person",
                ["Melodic Techno", "Electronic"],
                2005,
                "Germany",
                "lbl_kompakt",
                "ag_primary",
                "prd_stephanbodzin",
                "std_funkhaus",
            ),
            (
                "art_tangerinedream",
                "Tangerine Dream",
                "Group",
                ["Berlin School", "Ambient"],
                1967,
                "Germany",
                "lbl_virgin_emi",
                "ag_primary",
                "prd_connyplank",
                "std_hansa",
            ),
            (
                "art_zimmer_art",
                "Hans Zimmer",
                "Person",
                ["Cinematic", "Orchestral"],
                1977,
                "Germany",
                "lbl_dg",
                "ag_caa",
                "prd_zimmer",
                "std_air",
            ),
            (
                "art_maxrichter",
                "Max Richter",
                "Person",
                ["Post-Minimalism", "Classical"],
                1994,
                "UK / Germany",
                "lbl_dg",
                "ag_primary",
                "prd_brian",
                "std_air",
            ),
            (
                "art_beethoven_art",
                "Ludwig van Beethoven",
                "Person",
                ["Classical", "Symphonic"],
                1770,
                "Germany",
                "lbl_dg",
                None,
                None,
                "std_teldex",
            ),
            (
                "art_bach_art",
                "Johann Sebastian Bach",
                "Person",
                ["Baroque", "Polyphony"],
                1685,
                "Germany",
                "lbl_dg",
                None,
                None,
                "std_emilberliner",
            ),
            # === NETHERLANDS ===
            (
                "art_tiesto",
                "Tiësto",
                "Person",
                ["EDM", "Trance", "Electro House"],
                1994,
                "Netherlands",
                "lbl_atlantic",
                "ag_wme",
                "prd_tiesto_prd",
                "std_wisseloord",
            ),
            (
                "art_armin",
                "Armin van Buuren",
                "Person",
                ["Trance", "Progressive House"],
                1996,
                "Netherlands",
                "lbl_armada",
                "ag_caa",
                None,
                "std_wisseloord",
            ),
            (
                "art_martingarrix",
                "Martin Garrix",
                "Person",
                ["EDM", "Dance-Pop", "Progressive"],
                2012,
                "Netherlands",
                "lbl_spinnin",
                "ag_wme",
                None,
                "std_wisseloord",
            ),
            # === FRANCE ===
            (
                "art_daftpunk",
                "Daft Punk",
                "Group",
                ["French House", "Electronic", "Disco"],
                1993,
                "France",
                "lbl_columbia",
                "ag_caa",
                "prd_daft_thomas",
                "std_motorbass",
            ),
            (
                "art_justice",
                "Justice",
                "Group",
                ["Electro House", "Synthwave"],
                2003,
                "France",
                "lbl_edbanger",
                "ag_primary",
                "prd_pedrowinter",
                "std_motorbass",
            ),
            (
                "art_phoenix",
                "Phoenix",
                "Group",
                ["Indie Pop", "Synthpop"],
                1999,
                "France",
                "lbl_because",
                "ag_wme",
                None,
                "std_motorbass",
            ),
            (
                "art_air_band",
                "Air",
                "Group",
                ["Space Pop", "Downtempo"],
                1995,
                "France",
                "lbl_virgin_emi",
                "ag_primary",
                None,
                "std_grandearmee",
            ),
            (
                "art_davidguetta",
                "David Guetta",
                "Person",
                ["EDM", "Dance-Pop"],
                2001,
                "France",
                "lbl_warner_rec",
                "ag_caa",
                None,
                "std_metropolis",
            ),
            (
                "art_gesaffelstein",
                "Gesaffelstein (Mike Lévy)",
                "Person",
                ["Industrial Techno", "Dark Wave"],
                2008,
                "France",
                "lbl_columbia",
                "ag_wme",
                None,
                "std_motorbass",
            ),
            # === SWEDEN & NORDICS ===
            (
                "art_abba",
                "ABBA",
                "Group",
                ["Europop", "Disco"],
                1972,
                "Sweden",
                "lbl_stockholm_rec",
                None,
                None,
                "std_maratone",
            ),
            (
                "art_avicii",
                "Avicii (Tim Bergling)",
                "Person",
                ["EDM", "Melodic House"],
                2008,
                "Sweden",
                "lbl_interscope",
                "ag_wme",
                None,
                "std_maratone",
            ),
            (
                "art_swedishhouse",
                "Swedish House Mafia",
                "Group",
                ["Progressive House", "EDM"],
                2008,
                "Sweden",
                "lbl_republic",
                "ag_wme",
                None,
                "std_maratone",
            ),
            (
                "art_robyn",
                "Robyn",
                "Person",
                ["Electropop", "Dance-Pop"],
                1995,
                "Sweden",
                "lbl_island",
                "ag_primary",
                "prd_max",
                "std_maratone",
            ),
            (
                "art_zaralarsson",
                "Zara Larsson",
                "Person",
                ["Dance-Pop", "R&B"],
                2013,
                "Sweden",
                "lbl_ten_music",
                "ag_wme",
                "prd_max",
                "std_maratone",
            ),
            (
                "art_bjork",
                "Björk",
                "Person",
                ["Art Pop", "Electronic", "Avant-Garde"],
                1977,
                "Iceland",
                "lbl_4ad",
                "ag_primary",
                None,
                "std_greenhouse",
            ),
            (
                "art_sigurros",
                "Sigur Rós",
                "Group",
                ["Post-Rock", "Ambient"],
                1994,
                "Iceland",
                "lbl_smekkleysa",
                "ag_wme",
                None,
                "std_greenhouse",
            ),
            # === JAPAN ===
            (
                "art_ymo",
                "Yellow Magic Orchestra (YMO)",
                "Group",
                ["Synthpop", "Electronic"],
                1978,
                "Japan",
                "lbl_victor_jp",
                None,
                "prd_sakamoto_prd",
                "std_sonytokyo",
            ),
            (
                "art_sakamoto",
                "Ryuichi Sakamoto",
                "Person",
                ["Ambient", "Classical", "Electronic"],
                1975,
                "Japan",
                "lbl_virgin_emi",
                "ag_primary",
                "prd_sakamoto_prd",
                "std_sonytokyo",
            ),
            (
                "art_hisaishi",
                "Joe Hisaishi",
                "Person",
                ["Cinematic", "Orchestral"],
                1981,
                "Japan",
                "lbl_dg",
                None,
                "prd_hisaishi_prd",
                "std_ghibli",
            ),
            (
                "art_nujabes",
                "Nujabes",
                "Person",
                ["Lo-Fi Hip-Hop", "Jazz Rap"],
                1998,
                "Japan",
                "lbl_victor_jp",
                None,
                "prd_nujabes_prd",
                "std_sonytokyo",
            ),
            (
                "art_babymetal",
                "BABYMETAL",
                "Group",
                ["Kawaii Metal", "J-Rock"],
                2010,
                "Japan",
                "lbl_sony_japan",
                "ag_uta",
                None,
                "std_sonytokyo",
            ),
            (
                "art_tatsuro",
                "Tatsuro Yamashita",
                "Person",
                ["City Pop", "Funk"],
                1975,
                "Japan",
                "lbl_warner_rec",
                None,
                None,
                "std_sonytokyo",
            ),
            # === SOUTH KOREA ===
            (
                "art_bts",
                "BTS",
                "Group",
                ["K-Pop", "Dance-Pop", "Hip-Hop"],
                2013,
                "South Korea",
                "lbl_hybe_corp",
                "ag_sbprojects",
                "prd_pdogg",
                "std_hybe_std",
            ),
            (
                "art_blackpink",
                "BLACKPINK",
                "Group",
                ["K-Pop", "EDM", "Trap"],
                2016,
                "South Korea",
                "lbl_yg_ent",
                "ag_wme",
                "prd_teddypark",
                "std_conway",
            ),
            (
                "art_newjeans",
                "NewJeans",
                "Group",
                ["K-Pop", "UK Garage", "R&B"],
                2022,
                "South Korea",
                "lbl_hybe_corp",
                "ag_caa",
                None,
                "std_hybe_std",
            ),
            (
                "art_straykids",
                "Stray Kids",
                "Group",
                ["K-Pop", "Electronic Rock"],
                2017,
                "South Korea",
                "lbl_jyp_ent",
                "ag_republic",
                None,
                "std_hybe_std",
            ),
            (
                "art_seventeen",
                "SEVENTEEN",
                "Group",
                ["K-Pop", "Synthpop", "Dance"],
                2015,
                "South Korea",
                "lbl_hybe_corp",
                "ag_kakaom",
                None,
                "std_hybe_std",
            ),
            # === INDIA ===
            (
                "art_arrahman_art",
                "A.R. Rahman",
                "Person",
                ["Cinematic", "Fusion", "Qawwali"],
                1992,
                "India",
                "lbl_yrf_music",
                "ag_caa",
                "prd_arrahman",
                "std_panchathan",
            ),
            (
                "art_diljit",
                "Diljit Dosanjh",
                "Person",
                ["Punjabi Pop", "Bhangra", "Urban"],
                2004,
                "India",
                "lbl_warner_rec",
                "ag_wme",
                None,
                "std_yashraj",
            ),
            (
                "art_divine",
                "DIVINE",
                "Person",
                ["Gully Rap", "Desi Hip-Hop"],
                2013,
                "India",
                "lbl_gully_gang",
                "ag_tm_talent",
                None,
                "std_yashraj",
            ),
            # === JAMAICA ===
            (
                "art_bobmarley",
                "Bob Marley & The Wailers",
                "Group",
                ["Reggae", "Roots", "Ska"],
                1963,
                "Jamaica",
                "lbl_island",
                None,
                "prd_leeperry",
                "std_tuffgong",
            ),
            (
                "art_kingtubby_art",
                "King Tubby",
                "Person",
                ["Dub", "Roots"],
                1968,
                "Jamaica",
                "lbl_trojan",
                None,
                "prd_kingtubby",
                "std_blackark",
            ),
            (
                "art_leeperry_art",
                "Lee 'Scratch' Perry",
                "Person",
                ["Dub", "Experimental"],
                1965,
                "Jamaica",
                "lbl_island",
                None,
                "prd_leeperry",
                "std_blackark",
            ),
            (
                "art_seanpaul",
                "Sean Paul",
                "Person",
                ["Dancehall", "Reggaeton"],
                1996,
                "Jamaica",
                "lbl_atlantic",
                "ag_caa",
                None,
                "std_tuffgong",
            ),
            # === NIGERIA & SOUTH AFRICA ===
            (
                "art_felakuti",
                "Fela Kuti",
                "Person",
                ["Afrobeat", "Jazz", "Funk"],
                1961,
                "Nigeria",
                "lbl_island",
                None,
                None,
                "std_abbey",
            ),
            (
                "art_burnaboy",
                "Burna Boy",
                "Person",
                ["Afrobeat", "Afropop"],
                2010,
                "Nigeria",
                "lbl_spaceship",
                "ag_caa",
                "prd_timbaland",
                "std_mavin_std",
            ),
            (
                "art_wizkid",
                "Wizkid",
                "Person",
                ["Afrobeats", "R&B"],
                2009,
                "Nigeria",
                "lbl_starboy",
                "ag_wme",
                "prd_sarz",
                "std_mavin_std",
            ),
            (
                "art_davido",
                "Davido",
                "Person",
                ["Afropop", "Amapiano"],
                2011,
                "Nigeria",
                "lbl_columbia",
                "ag_wme",
                None,
                "std_mavin_std",
            ),
            (
                "art_tems",
                "Tems",
                "Person",
                ["Afro-Soul", "R&B"],
                2018,
                "Nigeria",
                "lbl_rca",
                "ag_wme",
                None,
                "std_mavin_std",
            ),
            (
                "art_rema",
                "Rema",
                "Person",
                ["Afro-Rave", "Afropop"],
                2019,
                "Nigeria",
                "lbl_mavin",
                "ag_wme",
                "prd_donjazzy",
                "std_mavin_std",
            ),
            (
                "art_blackcoffee",
                "Black Coffee",
                "Person",
                ["Afro-House", "Deep House"],
                1994,
                "South Africa",
                "lbl_soulistic",
                "ag_wme",
                "prd_blackcoffee_prd",
                "std_soulistic_std",
            ),
            (
                "art_tyla",
                "Tyla",
                "Person",
                ["Popiano", "Amapiano", "R&B"],
                2019,
                "South Africa",
                "lbl_epic",
                "ag_caa",
                None,
                "std_soulistic_std",
            ),
            # === BRAZIL, COLOMBIA, PUERTO RICO & MEXICO ===
            (
                "art_jobim",
                "Antônio Carlos Jobim",
                "Person",
                ["Bossa Nova", "MPB", "Jazz"],
                1956,
                "Brazil",
                "lbl_somlivre",
                None,
                None,
                "std_nasnuvens",
            ),
            (
                "art_caetano",
                "Caetano Veloso",
                "Person",
                ["Tropicália", "MPB"],
                1965,
                "Brazil",
                "lbl_somlivre",
                None,
                None,
                "std_nasnuvens",
            ),
            (
                "art_anitta",
                "Anitta",
                "Person",
                ["Funk Carioca", "Latin Pop"],
                2010,
                "Brazil",
                "lbl_republic",
                "ag_wme",
                None,
                "std_nasnuvens",
            ),
            (
                "art_alok",
                "Alok",
                "Person",
                ["Brazilian Bass", "Slap House"],
                2004,
                "Brazil",
                "lbl_spinnin",
                "ag_wme",
                None,
                "std_nasnuvens",
            ),
            (
                "art_badbunny",
                "Bad Bunny",
                "Person",
                ["Reggaeton", "Latin Trap"],
                2016,
                "Puerto Rico",
                "lbl_rimas",
                "ag_uta",
                "prd_tainy",
                "std_criteria",
            ),
            (
                "art_rosalia",
                "Rosalía",
                "Person",
                ["Flamenco Pop", "Art Pop"],
                2013,
                "Spain",
                "lbl_columbia",
                "ag_wme",
                "prd_pharrell",
                "std_electric",
            ),
            (
                "art_jbalvin",
                "J Balvin",
                "Person",
                ["Reggaeton", "Latin Pop"],
                2009,
                "Colombia",
                "lbl_republic",
                "ag_sbprojects",
                "prd_ovydrums",
                "std_elalto",
            ),
            (
                "art_karolg",
                "Karol G",
                "Person",
                ["Reggaeton", "Latin Trap"],
                2012,
                "Colombia",
                "lbl_interscope",
                "ag_uta",
                "prd_ovydrums",
                "std_elalto",
            ),
            (
                "art_pesopluma",
                "Peso Pluma",
                "Person",
                ["Corridos Tumbados", "Regional Mexican"],
                2020,
                "Mexico",
                "lbl_interscope",
                "ag_caa",
                None,
                "std_criteria",
            ),
            # === AUSTRALIA ===
            (
                "art_tameimpala",
                "Tame Impala",
                "Person",
                ["Psychedelic Pop", "Synthpop"],
                2007,
                "Australia",
                "lbl_modular",
                "ag_wme",
                "prd_kevinparker",
                "std_studios301",
            ),
            (
                "art_flume",
                "Flume",
                "Person",
                ["Future Bass", "Wonky Electronic"],
                2011,
                "Australia",
                "lbl_futureclassic",
                "ag_wme",
                None,
                "std_studios301",
            ),
            (
                "art_rufus",
                "Rüfüs Du Sol",
                "Group",
                ["Live Electronic", "Deep House"],
                2010,
                "Australia",
                "lbl_warner_rec",
                "ag_caa",
                None,
                "std_studios301",
            ),
            # === CANADA ===
            (
                "art_drake",
                "Drake",
                "Person",
                ["Hip-Hop", "R&B", "Toronto Sound"],
                2006,
                "Canada",
                "lbl_republic",
                "ag_wme",
                "prd_40",
                "std_metalworks",
            ),
            (
                "art_weeknd",
                "The Weeknd",
                "Person",
                ["R&B", "Pop", "Synthwave"],
                2010,
                "Canada",
                "lbl_republic",
                "ag_caa",
                "prd_max",
                "std_conway",
            ),
            (
                "art_deadmau5",
                "deadmau5",
                "Person",
                ["Progressive House", "Electro"],
                2005,
                "Canada",
                "lbl_virgin_emi",
                "ag_uta",
                None,
                "std_metalworks",
            ),
            (
                "art_kaytranada",
                "KAYTRANADA",
                "Person",
                ["Neo-Soul", "House", "Hip-Hop"],
                2010,
                "Canada",
                "lbl_rca",
                "ag_wme",
                "prd_kaytranada_prd",
                "std_metalworks",
            ),
            (
                "art_arcadefire",
                "Arcade Fire",
                "Group",
                ["Indie Rock", "Art Rock"],
                2001,
                "Canada",
                "lbl_columbia",
                "ag_wme",
                None,
                "std_metalworks",
            ),
        ]

        for (
            aid,
            name,
            atype,
            genres,
            since,
            country,
            cur_lbl,
            cur_ag,
            pref_prd,
            pref_std,
        ) in artists_corpus:
            art = Artist(
                id=aid,
                name=name,
                type=atype,
                genres=genres,
                active_since=since,
                country=country,
            )
            add_ent(art)

            if cur_lbl:
                edges.append(
                    RelationshipEdge(
                        source_id=aid,
                        target_id=cur_lbl,
                        rel_type=RelationshipType.SIGNED_TO,
                        start_year=since,
                        weight=1.0,
                        is_current=True,
                    )
                )

            if cur_ag:
                edges.append(
                    RelationshipEdge(
                        source_id=aid,
                        target_id=cur_ag,
                        rel_type=RelationshipType.REPRESENTED_BY,
                        weight=1.0,
                        is_current=True,
                    )
                )

            if pref_std:
                edges.append(
                    RelationshipEdge(
                        source_id=aid,
                        target_id=pref_std,
                        rel_type=RelationshipType.RECORDED_AT,
                        weight=0.9,
                    )
                )

            if pref_prd:
                edges.append(
                    RelationshipEdge(
                        source_id=aid,
                        target_id=pref_prd,
                        rel_type=RelationshipType.PRODUCED_BY,
                        weight=0.95,
                    )
                )

        # =========================================================================
        # 6. GLOBAL CROSS-BORDER COLLABORATIONS & CORRIDORS
        # =========================================================================
        cross_border_collabs = [
            # Swedish Pop Export Bridges
            ("art_taylor", "prd_max", 2012, 0.98),
            ("art_weeknd", "prd_max", 2015, 0.98),
            ("art_dua", "prd_max", 2020, 0.95),
            ("art_kendrick", "prd_goransson", 2018, 0.95),
            ("art_burnaboy", "prd_goransson", 2020, 0.85),
            # German Studio & Acoustic Bridges
            ("art_davidbowie", "art_brian", 1977, 0.98),
            ("art_depechemode", "art_davidbowie", 1983, 0.70),
            ("art_kraftwerk", "art_daftpunk", 1997, 0.90),
            ("art_kraftwerk", "art_aphex", 1995, 0.85),
            ("art_nilsfrahm_art", "art_maxrichter", 2018, 0.85),
            ("art_nilsfrahm_art", "art_modeselektor", 2015, 0.80),
            ("art_zimmer_art", "art_maxrichter", 2020, 0.80),
            ("art_stephanbodzin_art", "art_borisbrejcha", 2019, 0.85),
            # K-Pop x Global Western Bridges
            ("art_bts", "art_coldplay", 2021, 0.90),
            ("art_blackpink", "art_dua", 2018, 0.85),
            ("art_blackpink", "art_rosalia", 2024, 0.90),
            ("art_seventeen", "art_tori_kelly", 2022, 0.75),
            # Afrobeats x Western/Latin Bridges
            ("art_drake", "art_wizkid", 2016, 0.98),
            ("art_rema", "art_rosalia", 2023, 0.85),
            ("art_burnaboy", "art_phoebe", 2022, 0.65),
            ("art_wizkid", "art_tems", 2020, 0.98),
            ("art_tyla", "art_travisscott", 2023, 0.90),
            ("art_blackcoffee", "art_drake", 2017, 0.95),
            # Latin America x Global Urban
            ("art_badbunny", "art_drake", 2018, 0.95),
            ("art_rosalia", "art_badbunny", 2021, 0.90),
            ("art_rosalia", "art_travisscott", 2020, 0.90),
            ("art_badbunny", "art_jbalvin", 2019, 0.98),
            ("art_karolg", "art_tiesto", 2021, 0.85),
            ("art_pesopluma", "art_anitta", 2023, 0.85),
            # Indian & Global Fusion
            ("art_arrahman_art", "art_zimmer_art", 2015, 0.80),
            ("art_diljit", "art_sia", 2023, 0.85),
            # Australia x Global
            ("art_tameimpala", "art_travisscott", 2018, 0.90),
            ("art_tameimpala", "art_dua", 2024, 0.95),
            ("art_flume", "art_beck", 2016, 0.80),
            # UK x US x Canada Electronic Titans
            ("art_drake", "art_future", 2015, 0.95),
            ("art_drake", "art_21savage", 2022, 0.95),
            ("art_kanye", "art_drake", 2021, 0.70),
            ("art_kanye", "art_kendrick", 2016, 0.85),
            ("art_eminem", "art_drdre", 1999, 0.98),
            ("art_taylor", "art_phoebe", 2021, 0.80),
            ("art_fourtet", "art_skrillex_art", 2023, 0.98),
            ("art_fourtet", "art_bicep", 2021, 0.85),
            ("art_flyinglotus", "art_kendrick", 2014, 0.90),
            ("art_kaytranada", "art_phoebe", 2021, 0.70),
        ]

        for a1, a2, yr, w in cross_border_collabs:
            if a1 in seen_entities and a2 in seen_entities:
                edges.append(
                    RelationshipEdge(
                        source_id=a1,
                        target_id=a2,
                        rel_type=RelationshipType.COLLABORATED_WITH,
                        start_year=yr,
                        weight=w,
                        metadata={"collab_type": "international_release"},
                    )
                )

        return entities, edges
